---
- name: Secure environment
  hosts: all
  gather_facts: False
  become: True
  become_user: root
  become_method: sudo

  tasks:
  - name: SSHD - Disable root login 
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: ^(#)?PermitRootLogin
      line: PermitRootLogin no
  - name: SSHD - Allow user
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: ^(AllowUsers)?
      line: AllowUsers {{ansible_user}}
  - name: SSHD - Restart service
    systemd:
      state: restarted
      name: sshd
